apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tracing-collector
  namespace: tracing-collector
spec:
  dnsNames:
  - tracing-collector.hosted.blahonga.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tracing-collector
