apiVersion: v1
kind: Service
metadata:
  labels:
    external-dns.blahonga.me/publish: "yes"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'tracing-collector.hosted.blahonga.me.'
  name: cluster-collector-loadbalancer
  namespace: tracing-collector
spec:
  ports:
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - appProtocol: http
    name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: tracing-collector.cluster-collector
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry
  sessionAffinity: None
  type: LoadBalancer